# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [9]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a)
print(a.sum()) #45
print(np.sum(a))#45
print(sum(a)) #[ 5  7  9 11 13]

[[0 1 2 3 4]
 [5 6 7 8 9]]
45
45
[ 5  7  9 11 13]


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [ ]:
import numpy as np

In [15]:

a = np.random.random((5, 5))
print(a)
amin, amax = a.min(), a.max()
a = (a - amin)/(amax - amin)
print('--------')
print(a)

[[0.43704121 0.27381051 0.40618283 0.50261102 0.99432414]
 [0.46129495 0.64849337 0.10913332 0.15073381 0.96361902]
 [0.20693836 0.24167041 0.74589612 0.6870113  0.69390911]
 [0.62364769 0.13247691 0.56502859 0.85634403 0.2082036 ]
 [0.39930392 0.8563403  0.36404749 0.90373665 0.32966419]]
--------
[[0.37043752 0.1860358  0.33557681 0.44451172 1.        ]
 [0.39783696 0.609315   0.         0.04699606 0.96531242]
 [0.11049034 0.14972713 0.71935088 0.6528287  0.66062116]
 [0.58124684 0.02637124 0.51502485 0.84412388 0.11191968]
 [0.3278057  0.84411966 0.28797651 0.89766332 0.2491337 ]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [38]:
b=np.arange(10)
c=max(b)
b[c]=-1
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, -1])