作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [3]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?

In [38]:
X=np.isnan(math_score)   
X2=np.logical_not(X)
math_score2=math_score[X2]
math_score2

array([60., 85., 60., 68., 60.])

In [45]:
print("English---","mean:",np.mean(english_score),"Max:",np.max(english_score),"Min:",np.min(english_score),"std:",np.std(english_score))
print("Math---","mean:",np.mean(math_score2),"Max:",np.max(math_score2),"Min:",np.min(math_score2),"std:",np.std(math_score2))
print("Chinese---","mean:",np.mean(chinese_score),"Max:",np.max(chinese_score),"Min:",np.min(chinese_score),"std:",np.std(chinese_score))

English--- mean: 67.16666666666667 Max: 89 Min: 48 std: 13.433995020924426
Math--- mean: 66.6 Max: 85.0 Min: 60.0 std: 9.707728879609279
Chinese--- mean: 75.33333333333333 Max: 90 Min: 65 std: 8.825468196582484


In [4]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?

In [56]:
math_score_new=np.append(math_score2,55)
print("math_score_new---","mean:",np.mean(math_score_new),"Max:",np.max(math_score_new),"Min:",np.min(math_score_new),"std:",np.std(math_score_new))


math_score_new--- mean: 64.66666666666667 Max: 85.0 Min: 55.0 std: 9.860132971832694


In [5]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [63]:
c1=np.corrcoef(english_score,chinese_score)
c2=np.corrcoef(math_score_new,chinese_score)
print(c1)
print(c2)

[[1.         0.97792828]
 [0.97792828 1.        ]]
[[1.         0.63522861]
 [0.63522861 1.        ]]
